function [] = giveInstruction(window, keys, responseHandler, constants, expt, expParams, stim)


%%
switch expt
    case 'occularDominance'
        showPromptAndWaitForResp(window, 'This first phase is to get you comfortable wearing the glasses.',...
            keys,constants,responseHandler);
        showPromptAndWaitForResp(window, 'You will see arrows pointing either left or right.',...
            keys,constants,responseHandler);
        showPromptAndWaitForResp(window, ['Use the arrow keys to say which direction you think the arrow faces.\n', ...
            'Please respond as soon as you are sure of the direction.'],...
            keys,constants,responseHandler);
        showPromptAndWaitForResp(window, 'Keep your eyes focused on the white cross in the center.',...
            keys,constants,responseHandler);
        %%
    case 'visualRecollection'
        
        showPromptAndWaitForResp(window, ['You will now have a chance to practice the main experiment.\n',...
            'There will be a study phase and a test phase.'],...
            keys,constants,responseHandler);
        showPromptAndWaitForResp(window, 'You will see hidden objects emerge from flashing squares',...
            keys,constants,responseHandler);
                
        showPromptAndWaitForResp(window, ['As soon as you are certain that an object is emerging, press the ''j'' key.\n',...
            'Please press the key before you are able to identify the object.'],...
            keys,constants,responseHandler);
        showPromptAndWaitForResp(window, ['After each trial, you will be asked about how well you could see the object.\n',...
            'Respond with the following options.\n\n',...
            'no image detected - 0\n',...
            'possibly saw, couldn''t identify - 1\n',...
            'definitely saw, but unsure what it was (could possibly guess) - 2\n',...
            'definitely saw, could identify - 3\n',...
            '\nWhen objects are emerging, you should wait until you can give a response of 2\n',...
            'but respond before you would give a response of 3.\n', ...
            '\nUse the keypad to indicate your response.\n'],...
            keys,constants,responseHandler);

        showPromptAndWaitForResp(window, ['On some trials, there will be no object\n',...
            'If you haven''t seen an object and think that one won''t appear, press ''f'''],...
            keys,constants,responseHandler);
        showPromptAndWaitForResp(window, 'Finally, always keep your eyes focused on the white cross in the center',...
            keys,constants,responseHandler);
        %%
    case 'NAME'
        
        showPromptAndWaitForResp(window, 'This is the first test of your memory this experiment!',...
            keys,constants,responseHandler);
        showPromptAndWaitForResp(window, ['You will first see an object.\n',...
            'However, only a small, circular part of that object will be visible.\n',...
            'Some of these parts will come from objects that you studied, but others will be new.\n',...
            'Your task will be to name the partially hidden object.\n',...
            'Feel free to use your memory of the objects you studied if you think it will help.\n',...
            '\nAn example will be shown on the next slide.'],...
            keys,constants,responseHandler);
        
        showPromptAndWaitForResp(window, ...
            'Type your responses with the keyboard, and press Enter when you have finished typing.',...
            keys,constants,responseHandler);
        
        stims = makeTexs(212, window, stim, 'NAME', 215);
        
        elicitCueName(window, responseHandler, stims.tex, ...
            keys.enter+keys.escape+keys.name+keys.bkspace+keys.space, ...
            constants, '\ENTER', 'present', 'name', 120);
        Screen('Close', stims.tex);
        
        showPromptAndWaitForResp(window, 'In that case, the correct answer would have been ''lightswitch''',...
            keys,constants,responseHandler);
       
        showPromptAndWaitForResp(window, 'Please name the following objects',...
            keys,constants,responseHandler);
        
    case 'NOISE'
        
        showPromptAndWaitForResp(window, ['This is the second set of memory tests in this experiment!\n',...
            'You will have two kinds of tasks.'],...
            keys,constants,responseHandler);
        
        showPromptAndWaitForResp(window, ['You will see the same kinds of partially hidden objects that you just tried to name.\n',...
            'Try to think of the identity of the hidden object as knowing the name may help you in your second task.\n',...
            '\nTo check that you are trying to think of the name, you will sometimes be asked to name the object.'],...
            keys,constants,responseHandler);        
        
        showPromptAndWaitForResp(window, ['Other times, instead of being asked to provide the object name, visual noise will appear.\n',...
            'An object may emerge from that noise. When an object does, it will be the same one that you would have just tried to name\n',...
            'Your task is simply to press Enter if an object is emerging. If there is no object, just wait.\n',...
            '\nAn Example will be shown on the next slide'], ...
            keys,constants,responseHandler);
        showPromptAndWaitForResp(window, 'Press Enter only if you see an object', ...
            keys,constants, responseHandler);
        
        stims = makeTexs(212, window, stim, 'NOISE',215);
        
        alpha_img = [zeros(1,10), .05:.05:1, ones(1,100)];
        elicitBCFS(window, responseHandler,...
            stims.tex, [1, 1],...
            keys.enter+keys.escape, stim, constants, stim.image_dst_rect,...
            0, '\ENTER', 'visualRecollection',...
            length(alpha_img), 'Press Enter only if you see an object', alpha_img,'white');
        Screen('Close', stims.tex);
                
        showPromptAndWaitForResp(window, ['If that had been a real trial, you would have wanted to press Enter.\n',...
            'Only press Enter when you see an object. Otherwise, just wait.'],...
            keys,constants,responseHandler);
        
        showPromptAndWaitForResp(window, ['You will sometimes see visual noise without being asked to name an object.\n',...
            'In those cases, your task is the same. Press ENTER if you see an object, but do not respond if there is no object.'],...
            keys,constants,responseHandler);
                
        showPromptAndWaitForResp(window, 'The practice will begin after you press SPACE',...
            keys,constants,responseHandler);
        
end

iti(window, 1, stim);


end